//
//  Students.swift
//  TableViewPlay
//
//  Created by Josh & Erica on 1/31/17.
//  Copyright © 2017 Josh McDonald. All rights reserved.
//

import Foundation

class Students {
    static func studentArray() -> [String] {
return ["Carl",
        "Domingo",
        "Sterling",
        "Sam",
        "Erik",
        "Doug",
        "Snow",
        "Logan",
        "Mortensen",
        "Dakota",
        "Ted",
        "Jared",
        "Herbert",
        "Lou",
        "Carl",
        "Domingo",
        "Sterling",
        "Sam",
        "Erik",
        "Doug",
        "Snow",
        "Logan",
        "Mortensen",
        "Dakota",
        "Ted",
        "Jared",
        "Herbert",
        "Lou",
        "Carl",
        "Domingo",
        "Sterling",
        "Sam",
        "Erik",
        "Doug",
        "Snow",
        "Logan",
        "Mortensen",
        "Dakota",
        "Ted",
        "Jared",
        "Herbert",
        "Lou",
        "Carl",
        "Domingo",
        "Sterling",
        "Sam",
        "Erik",
        "Doug",
        "Snow",
        "Logan",
        "Mortensen",
        "Dakota",
        "Ted",
        "Jared",
        "Herbert",
        "Lou",
        "Carl",
        "Domingo",
        "Sterling",
        "Sam",
        "Erik",
        "Doug",
        "Snow",
        "Logan",
        "Mortensen",
        "Dakota",
        "Ted",
        "Jared",
        "Herbert",
        "Lou",
        "Carl",
        "Domingo",
        "Sterling",
        "Sam",
        "Erik",
        "Doug",
        "Snow",
        "Logan",
        "Mortensen",
        "Dakota",
        "Ted",
        "Jared",
        "Herbert",
        "Lou"]
}
}
